language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
notifications:
  irc: "irc.freenode.org#asciidoctor"
script:
  - bash test-asciidoctor-master.sh
  - mvn test
matrix:
  allow_failures:
    - script: mvn test #current release could fail because of backward incompatibility
