language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
before_script: unset GEM_PATH GEM_HOME JRUBY_OPTS
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
install: ./gradlew assemble
script: ./gradlew -S check && bash test-asciidoctor-upstream.sh
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#asciidoctor"
