os: linux
dist: trusty
language: java
matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk7
      dist: precise
    - jdk: openjdk7
      dist: precise
    - os: osx

addons:
  hosts:
    - asciidoctorj-builder
  hostname: asciidoctorj-builder
  apt:
    packages:
      - graphviz

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi

install: ./gradlew -S -Pskip.signing assemble

before_script: unset GEM_PATH GEM_HOME JRUBY_OPTS

script: ./gradlew -S -Pskip.signing check && bash test-asciidoctor-upstream.sh
