dist: precise
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_script: unset GEM_PATH GEM_HOME JRUBY_OPTS
before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
  - (cat /etc/hosts ; echo 127.0.0.1 $(hostname)) | sudo tee /etc/hosts
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
install: ./gradlew -S -Pskip.signing assemble
script: ./gradlew -S -Pskip.signing check && bash test-asciidoctor-upstream.sh
after_success: if [ "${TRAVIS_BRANCH}" = "asciidoctorj-1.6.0" -a "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_JDK_VERSION}" = "oraclejdk8" ]; then ./gradlew clean build artifactoryPublish -x test ; fi
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#asciidoctor"
env:
  - secure: "WYU2AptOM6CIiIykVUCj2Ca4umapAl2Qxv8sQDDTNuv9gVHk1rtU42kD6oqS/YoID0QoPy8g6Ggyvy1MF0wMpL4Vvu8pLnbLiYoJtmecpLHB0UZ1UixsgWL7bHExrh+ciCjjqliN9C0rUnmiDHj9Ald2VSWH6Vvcl2YG67Pbl+c="
