language: java
before_script:
  - unset GEM_PATH GEM_HOME JRUBY_OPTS
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
#env:
#  global:
#    - JAVA_OPTS="-Xms128m -Xmx512m --XX:MaxPermSize=256m -XX:-UseGCOverheadLimit"
notifications:
  irc:
    channels:
      - "irc.freenode.org#asciidoctor"
script:
  - mvn clean test -DforkMode=always
  - bash test-asciidoctor-upstream.sh
#matrix:
#  allow_failures:
#    - script: mvn test #current release could fail because of backward incompatibility
